-- Placeholder kept to preserve migration history.
-- The simulated catalog backfill was moved out of normal migrations because it
-- mutates production data. Apply the manual test seed instead:
-- scripts/sql/test-checkout-simulated-catalog.sql
